config/routes.rb
Rails.application.routes.draw do

  devise_for :providers, :controllers => { registrations: 'providers/registrations', sessions: 'providers/sessions', passwords: 'providers/passwords'}
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticated :user do
    root 'users#index'
  end

  authenticated :provider do
    root 'providers#index'
  end

  get '/', to: 'pages#homepage'
  get '/homepage', to: 'pages#homepage', as: 'homepage'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/about', to: 'pages#about', as: 'about'

  get '/urgent', to: 'users#urgent', as: 'urgent'
  get '/result', to: 'users#result', as: 'result'
  get '/electricians', to: 'users#electricians', as: 'electricians'

  resources :users, only: [:index, :show] do
    member do
      resources :conversations
    end
    member do
      resources :messages, only: [:new, :create, :destroy]
    end
  end

  resources :providers, only: [:index, :show] do
    member do
      resources :comments
    end
    member do
      get '/allmessages', to: 'conversations#allmessages', as: 'allmessages'
      get '/showmessages/:conversation_id', to: 'conversations#showmessages', as: 'showmessages'
    end
    member do
      resources :schedules, only: [:show, :new, :create, :update, :edit]
    end
    member do
      post 'like'
      delete 'unlike'
      put 'book'
    end
  end

  resources :joblistings do
    member do
      put 'accept'
      put 'decline'
    end
  end
  resources :invoices

  namespace 'admin' do
    resources :joblistings
    resources :invoices

    resources :providers, only: [:index]
    resources :users, only: [:index]
    get 'statistics'
  end

  resources :payments, only: [:new, :show, :create]

end

app/models/joblisting.rb
class Joblisting < ApplicationRecord

  belongs_to :user
  has_many :job_attaches, dependent: :destroy
  accepts_nested_attributes_for :job_attaches, reject_if: :all_blank, allow_destroy: true
  has_one :invoice

  before_save do
    issue.gsub!(/[\[\]\"]/, '') if attribute_present?('issue')
    fixture.gsub!(/[\[\]\"]/, '') if attribute_present?('fixture')
  end

  enum status: {
    'created':    1,
    'pending':    2,
    'booked':     3,
    'completed':  4,
    'cancel':     5
  }

end

app/controllers/admin/joblistings_controller.rb
class Admin::JoblistingsController < ApplicationController

  before_action :is_admin?

  def index
    @joblistings = Joblisting.all.page(params[:page]).per_page(10)
    @all_projects_total_cost = 0
    Invoice.all.map { |invoice| @all_projects_total_cost += invoice.price }
  end

  def edit; end

  def update; end

  def destroy; end

  private

  def is_admin?
    if current_user && current_user.is_admin == false
      redirect_to users_path
    elsif current_provider
      redirect_to providers_path
    elsif current_user.nil? && current_provider.nil?
      redirect_to homepage_path
    end
  end

end

app/controllers/joblistings_controller.rb
class JoblistingsController < ApplicationController

  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :authenticate_provider!, only: %i[accept decline]

  before_action :set_joblisting, except: %i[index new create]

  def index
    @joblistings = if current_provider
                     current_provider.joblistings.page(params[:page]).per_page(10)
                   else
                     Joblisting.all.page(params[:page]).per_page(10)
                   end
  end

  def show; end

  def new
    @joblisting = Joblisting.new
  end

  def create
    @joblisting = Joblisting.new(joblisting_params)
    @joblisting.user = current_user
    @joblisting.status = 'created'
    if @joblisting.save
      redirect_to result_path(job_date: @joblisting.date)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @joblisting.update(joblisting_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy; end

  def accept
    @joblisting.update(status: 'booked')
    @conversation = Conversation.where(provider_id: current_provider.id, user_id: @joblisting.user_id).first_or_create
    @message = Message.new(conversation_id: @conversation.id, provider_id: current_provider.id, user_id: @joblisting.user_id, body: 'I have accepted your request!')
    @message.body = current_provider.firstname + ' : ' + @message.body
    @message.save
    @message.update(providerticks: 'blue')
    redirect_to providers_path
  end

  def decline
    @joblisting.update(provider_id: nil, status: 'cancel')
    @conversation = Conversation.where(provider_id: current_provider.id, user_id: @joblisting.user_id).first_or_create
    @message = Message.new(conversation_id: @conversation.id, provider_id: current_provider.id, user_id: @joblisting.user_id, body: 'I have declined your request. Please find another provider. Thank you!')
    @message.body = current_provider.firstname + ' : ' + @message.body + " #{view_context.link_to('View your Joblsitings here!', users_path)} "
    @message.save
    @message.update(providerticks: 'blue')
    redirect_to providers_path
  end

  private

  def joblisting_params
    params.require(:joblisting).permit(:description, :num_fixture, :job_address, :time, :date, :housing, fixture: [], issue: [], job_attaches_attributes: %i[id title image joblisting_id _destroy])
  end

  private

  def set_joblisting
    @joblisting = Joblisting.find(params[:id])
  end

end

app/helpers/joblistings_helper.rb
module JoblistingsHelper

  def checked_i(area)
    @joblisting.issue.nil? ? false : @joblisting.issue.match(area)
  end

  def checked_f(area)
    @joblisting.fixture.nil? ? false : @joblisting.fixture.match(area)
  end

end

app/views/joblistings/edit.html.erb
<div class="row" id="whole-form">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 ">
    <%= bootstrap_form_for @joblisting, html: {multipart: true, class: "panel panel-primary"}, method: :put do |f| %>
    <div class="panel-heading" id="job-heading"><h4>Edit Job Request </h4> </div>
    <div class="form-padding">
      <div class='field'>
        <h4 class="question">What needs to be done?</h4>
        <%= label_tag 'issue_install', 'Installation' %>
        <%= check_box_tag 'joblisting[issue][]', 'Installation', checked_i('Installation'), id: 'issue_install' %>

        <%= label_tag 'issue_repair', 'Repair' %>
        <%= check_box_tag 'joblisting[issue][]', 'Repair', checked_i('Repair'), id: 'issue_repair' %>

        <%= label_tag 'issue_replace', 'Replace' %>
        <%= check_box_tag 'joblisting[issue][]', 'Replace', checked_i('Replace'), id: 'issue_replace' %>
      </div>

      <br />

      <div class='field'>
        <h4 class="question">What type of fixtures do you require?</h4>
        <%= label_tag 'fixture_wiring', 'Wiring' %>
        <%= check_box_tag 'joblisting[fixture][]', 'Wiring', checked_f('Wiring'), id: 'fixture_wiring' %>

        <%= label_tag 'fixture_light', 'Lights' %>
        <%= check_box_tag 'joblisting[fixture][]', 'Lights', checked_f('Lights'), id: 'fixture_light' %>

        <%= label_tag 'fixture_switch', 'Switches' %>
        <%= check_box_tag 'joblisting[fixture][]', 'Switches', checked_f('Switches'), id: 'fixture_switch' %>
      </div>

      <br />

      <div class="field">
        <h4 class="question"><%= f.label :number_of_fixtures_required %></h4>
        <%= f.select :num_fixture, ['1','2','3','4'] %>
      </div>

      <br />

      <div class='field'>
        <h4 class="question">When does it need to be done?</h4>
        <%= f.select :date, ['Within 5 days', 'Within 2 weeks', 'Within 1 month'] %>
      </div>

      <br />

      <div class="field">
        <%= f.select :time, ['Morning','Afternoon','Evening'] %>
      </div>

      <br />

      <div class='field'>
        <h4 class="question">What type of property do you stay in?</h4>
        <%= f.select :housing, ['HDBs', 'Condo', 'Landed'] %>
      </div>

      <br>
        <h4 class="question">Upload Job Image</h4>
        <div class="job_attaches">
          <%= f.fields_for :job_attaches do |job_attach| %>
            <%= render 'partials/job_attachment', f: job_attach %>
          <% end %>
          <br>
          <%= link_to_add_association 'Add Image', f, :job_attaches, partial: 'partials/job_attachment' %>

        </div>
      <br>

      <div class="field">
        <%= f.text_area :description, autofocus: true, placeholder: 'Description' %>
      </div>

      <div class="field">
        <%= f.text_area :job_address, autofocus: true, placeholder: 'Job Address' %>
      </div>

      <div class='actions'>
        <%= f.submit "Edit Job", class:"btn btn-success btn-block"  %>
      </div>

    <% end %>
  </div>
</div>

app/views/joblistings/index.html.erb
<div id='joblisting-index', class='container'>
  <br><br>
  <div id='joblisting-index-header'><h3>All Jobs</h3></div>
  <div class="panel panel-default">
   <div class="panel-heading"></div>
    <table class="table">
      <tr>
        <td>#</td>
        <td>Date</td>
        <td>Summary</td>
        <td>Job Status</td>
        <td>Invoice Status</td>
        <td>Project Value S$</td>
      </tr>
      <% @joblistings.each_with_index do |joblisting, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= joblisting.created_at.strftime("%F") %></td>
          <td><%= link_to "#{joblisting.description.capitalize}", joblisting_path(joblisting) %></td>
          <td><%= joblisting.status.capitalize %></td>
          <% if joblisting.status == 'completed' %>
            <td><%= joblisting.invoice.status.capitalize %></td>
            <td><%= number_with_delimiter(joblisting.invoice.price) %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>
      <div>
        <tr class='last-row'>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </div>
    </table>
  </div>
</div>
<%= will_paginate @joblistings %> 

app/views/joblistings/new.html.erb
<div class="row" id="whole-form">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 ">
    <%= bootstrap_form_for @joblisting, html: {multipart: true, class: "panel panel-primary"}, method: :post do |f| %>
    <div class="panel-heading" id="job-heading"><h4>New Job Request </h4> </div>
    <div class="form-padding">
      <div class='field'>
        <h4 class="question">What needs to be done?</h4>
        <%= label_tag 'issue_install', 'Installation' %>
        <%= check_box_tag 'joblisting[issue][]', 'Installation', checked_i('Installation'), id: 'issue_install' %>

        <%= label_tag 'issue_repair', 'Repair' %>
        <%= check_box_tag 'joblisting[issue][]', 'Repair', checked_i('Repair'), id: 'issue_repair' %>

        <%= label_tag 'issue_replace', 'Replace' %>
        <%= check_box_tag 'joblisting[issue][]', 'Replace', checked_i('Replace'), id: 'issue_replace' %>
      </div>

      <br/>

      <div class='field'>
        <h4 class="question">What type of fixtures do you require?</h4>
        <%= label_tag 'fixture_wiring', 'Wiring' %>
        <%= check_box_tag 'joblisting[fixture][]', 'Wiring', checked_f('Wiring'), id: 'fixture_wiring' %>

        <%= label_tag 'fixture_light', 'Lights' %>
        <%= check_box_tag 'joblisting[fixture][]', 'Lights', checked_f('Lights'), id: 'fixture_light' %>

        <%= label_tag 'fixture_switch', 'Switches' %>
        <%= check_box_tag 'joblisting[fixture][]', 'Switches', checked_f('Switches'), id: 'fixture_switch' %>
      </div>

      <br/>

      <div class="field">
        <h4 class="question"><%= f.label :number_of_fixtures_required %></h4>
        <%= f.select :num_fixture, ['1','2','3','4'] %>
      </div>

      <br/>

      <div class='field'>
        <h4 class="question">When does it need to be done?</h4>
        <%= f.select :date, ['Within 5 days', 'Within 2 weeks', 'Within 1 month'] %>
      </div>

      <br/>

      <div class="field">
        <%= f.select :time, ['Morning','Afternoon','Evening'] %>
      </div>

      <br/>

      <div class='field'>
        <h4 class="question">What type of property do you stay in?</h4>
        <%= f.select :housing, ['HDBs', 'Condo', 'Landed'] %>
      </div>

      <br>
      <h4 class="question">Upload Job Image</h4>
      <div class="job_attaches">
        <%= f.fields_for :job_attaches do |job_attach| %>
        <%= render'partials/job_attachment', f: job_attach %>
        <% end %>
        <%= link_to_add_association 'Add Image', f, :job_attaches, partial: 'partials/job_attachment' %>

      </div>
      <br>

      <div class="field">
        <%= f.text_area :description, autofocus: true, placeholder: 'Description' %>
      </div>

      <div class="field">
        <%= f.text_area :job_address, autofocus: true, placeholder: 'Job Address' %>
      </div>

      <div class='actions'>
        <%= f.submit "Create Job", class:"btn btn-success btn-block" %>
      </div>

      <% end %>

    </div>

  </div>
</div>

app/views/joblistings/show.html.erb
<div class="container paper">
  <div class="row">
    <div class="col-xs-12">
      <head>
        <title>Job Dashboard</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      </head>
   
      <% if @joblisting.job_attaches.empty? %>
        <div class='image-section col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-1'>
          <%= image_tag 'default-job-image.png' %>
        </div>
      <% else %>
        <div class='image-section col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-1 carousel slide' id="myCarousel" data-ride="carousel">
          <ol class="carousel-indicators">
          <% unless @joblisting.job_attaches.count == 1 %>
            <% @joblisting.job_attaches.each_with_index do |job_attach, index| %>
              <% if index == 0 %>          
                <li data-target="#myCarousel" data-slide-to="#{index}" class="active"></li>
              <% else %>
                <li data-target="#myCarousel" data-slide-to="#{index}"></li>
              <% end %>
            <% end %>
          <% end %>
          </ol>

          <div class="carousel-inner">
            <% @joblisting.job_attaches.each_with_index do |job_attach, index| %>
              <% if index == 0 %>
                <div class="item active">  
                  <%= image_tag @joblisting.job_attaches.first.image %>
                </div>
              <% else %>
                <div class="item">
                  <%= image_tag job_attach.image %>
                </div>
              <% end %>
            <% end %>
          </div>
          <!-- Left and right controls -->
          <% unless @joblisting.job_attaches.count == 1  %>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
            <% end %>
        </div>
      <% end %>

      <div class='col-xs-12 col-sm-6'>
        <div class="panel panel-default product-show-summary">
          <div class="panel-heading"><h3>Summary</h3></div>
            <ul class="list-group">
              <li class="list-group-item"></li>             
              <li class="list-group-item">Description: <%= @joblisting.description.capitalize %></li>     
            </ul>
        </div>

        <body>
          <ul class="nav nav-tabs product-show">
            <li class="active"><a data-toggle="tab" href="#menu1">Job Scopes</a></li>
            <li><a data-toggle="tab" href="#menu2">Contact details</a></li>
            <li><a data-toggle="tab" href="#menu3">Status details</a></li>       
          </ul>

          <div class="tab-content dashboard-form">
            <div id="menu1" class="tab-pane fade in active">
              <div class="panel panel-default show-body">
                <div class="panel-heading"><h3>Job Scopes</h3></div>
                  <ul class="list-group">
                    <li class="list-group-item"></li>  
                    <li class="list-group-item">Issue: <%= @joblisting.issue.capitalize %></li>
                    <li class="list-group-item">Fixture: <%= @joblisting.fixture.capitalize %></li>
                    <li class="list-group-item">Number of fixture: <%= @joblisting.num_fixture %> </li>
                    <li class="list-group-item">Preferred starting date: <%= @joblisting.date %></li>
                    <li class="list-group-item">Preferred timing: <%= @joblisting.time %></li> 
                  </ul>
              </div>
            </div>

            <div id="menu2" class="tab-pane fade">
              <div class="panel panel-default show-body">
                <div class="panel-heading"><h3>Contact details</h3></div>
                  <ul class="list-group">
                    <li class="list-group-item"></li>              
                    <li class="list-group-item">Job address: <%= @joblisting.job_address.capitalize %> </li>
                    <li class="list-group-item">User name: <%= @joblisting.user.firstname.capitalize %> </li>  <li class="list-group-item">User email: <%= @joblisting.user.email %> </li>
                    <% if @joblisting.provider_id %>
                      <li class="list-group-item">Provider name: <%= Provider.find(@joblisting.provider_id).firstname.capitalize %> </li>
                      <li class="list-group-item">Provider contact: <%= Provider.find(@joblisting.provider_id).tel_num %> </li>
                    <% else %>
                      <li class="list-group-item">Provider name: No provider booked </li>
                      <li class="list-group-item">Provider contact: No provider booked </li>
                    <% end  %>
                  </ul>
              </div>
            </div>

            <div id="menu3" class="tab-pane fade">
              <div class="panel panel-default show-body">
                <div class="panel-heading"><h3>Status details</h3></div>
                  <ul class="list-group">
                    <li class="list-group-item"></li>              
                    <li class="list-group-item">Job status: <%= @joblisting.status.capitalize %> </li>
                    <% if @joblisting.invoice %>
                      <li class="list-group-item">Invoice ref: <%= @joblisting.invoice.invoice_ref %> </li>
                      <li class="list-group-item">Invoice status: <%= @joblisting.invoice.status %> </li>
                    <% else %>
                      <li class="list-group-item">Invoice ref: No invoice </li>
                      <li class="list-group-item">Invoice status: No invoice </li>
                    <% end  %>
                  </ul>
              </div>
            </div>
          </div>
        </body>

          <ul class="list-group date-data">
            <li>Created on: <%= @joblisting.created_at.strftime("%F") %></li>
            <li>Last updated on : <%= @joblisting.updated_at.strftime("%F") %></li>
          </ul>

          <% unless current_user == nil || @joblisting.user_id != current_user.id %>
            <div>
              <%= link_to "Edit", edit_joblisting_path(@joblisting), class:'btn btn-success btn-block' %>
            </div>
          <% end %>

    </div>
  </div>
</div>