config/routes.rb
Rails.application.routes.draw do

  devise_for :providers, :controllers => { registrations: 'providers/registrations', sessions: 'providers/sessions', passwords: 'providers/passwords'}
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticated :user do
    root 'users#index'
  end

  authenticated :provider do
    root 'providers#index'
  end

  get '/', to: 'pages#homepage'
  get '/homepage', to: 'pages#homepage', as: 'homepage'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/about', to: 'pages#about', as: 'about'

  get '/urgent', to: 'users#urgent', as: 'urgent'
  get '/result', to: 'users#result', as: 'result'
  get '/electricians', to: 'users#electricians', as: 'electricians'

  resources :users, only: [:index, :show] do
    member do
      resources :conversations
    end
    member do
      resources :messages, only: [:new, :create, :destroy]
    end
  end

  resources :providers, only: [:index, :show] do
    member do
      resources :comments
    end
    member do
      get '/allmessages', to: 'conversations#allmessages', as: 'allmessages'
      get '/showmessages/:conversation_id', to: 'conversations#showmessages', as: 'showmessages'
    end
    member do
      resources :schedules, only: [:show, :new, :create, :update, :edit]
    end
    member do
      post 'like'
      delete 'unlike'
      put 'book'
    end
  end

  resources :joblistings do
    member do
      put 'accept'
      put 'decline'
    end
  end
  resources :invoices

  namespace 'admin' do
    resources :joblistings
    resources :invoices

    resources :providers, only: [:index]
    resources :users, only: [:index]
    get 'statistics'
  end

  resources :payments, only: [:new, :show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :provider

end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user
  belongs_to :provider

  validates :user_id, uniqueness: { scope: :provider_id }

  has_many :messages, dependent: :destroy

end

app/models/invoice.rb
class Invoice < ApplicationRecord

  belongs_to :provider
  belongs_to :joblisting

  enum status: {
    'Awaiting Payment': 1,
    'Payment Received': 2,
    'Payment Released': 3
  }

end

app/models/job_attach.rb
class JobAttach < ApplicationRecord

  mount_uploader :image, JobImageUploader
  belongs_to :joblisting

end

app/models/joblisting.rb
class Joblisting < ApplicationRecord

  belongs_to :user
  has_many :job_attaches, dependent: :destroy
  accepts_nested_attributes_for :job_attaches, reject_if: :all_blank, allow_destroy: true
  has_one :invoice

  before_save do
    issue.gsub!(/[\[\]\"]/, '') if attribute_present?('issue')
    fixture.gsub!(/[\[\]\"]/, '') if attribute_present?('fixture')
  end

  enum status: {
    'created':    1,
    'pending':    2,
    'booked':     3,
    'completed':  4,
    'cancel':     5
  }

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :provider

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation
  belongs_to :user
  belongs_to :provider

end

app/models/provider.rb
class Provider < ApplicationRecord

  mount_uploader :avatar, ProviderAvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes
  has_many :invoices
  has_many :provider_attaches
  has_many :joblistings
  has_one :schedule
  has_many :conversations
  has_many :messages
  has_many :comments

  accepts_nested_attributes_for :provider_attaches, reject_if: :all_blank, allow_destroy: true

  scope :sort_exp, -> { order('experience DESC') }

  enum experience: {
    "< 1 year":       1,
    "1 to 3 years":   2,
    "3 to 5 years":   3,
    "> 5 years":      4
  }

end

app/models/provider_attach.rb
class ProviderAttach < ApplicationRecord

  mount_uploader :image, ProviderAttachUploader
  belongs_to :provider

end

app/models/schedule.rb
class Schedule < ApplicationRecord

  belongs_to :provider

  validates :date, :time, presence: true

  scope :weekends, -> { where(date: 'weekends') }
  scope :weekdays, -> { where(date: 'weekdays') }
  scope :alldays, -> { where(date: 'all') }

  before_save do
    date.gsub!(/[\[\]\"]/, '') if attribute_present?('date')
    time.gsub!(/[\[\]\"]/, '') if attribute_present?('time')
  end

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :joblistings
  has_many :likes
  has_many :conversations
  has_many :messages
  has_many :comments
  has_many :providers, through: :likes
  has_many :invoices, through: :joblistings

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authenticate_user!, only: %i[index show]
  before_action :authenticate_provider!, only: %i[allmessages showmessages]

  def index
    @conversations = Conversation.where(user_id: current_user.id)
    @conversation = Conversation.new
    @providers = Provider.all
    @message = Message.new
  end

  def show
    @conversation = Conversation.find(params[:id])
    if @conversation.messages.present?
      @messages = @conversation.messages.update(userticks: 'blue')
    end
    @message = Message.new(conversation_id: @conversation)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.user = current_user
    if @conversation.save
      redirect_to conversations_path
    else
      redirect_to conversations_path(current_user.id)
      flash[:error] = 'Conversation already exists'
    end
  end

  def allmessages
    @conversations = Conversation.where(provider_id: current_provider.id)
    @message = Message.new
  end

  def showmessages
    @conversation = Conversation.find(params[:conversation_id])
    if @conversation.messages.present?
      @messages = @conversation.messages.update(providerticks: 'blue')
    end
    @message = Message.new(conversation_id: @conversation)
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:provider_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def checked_d(area)
    @schedule.date.nil? ? false : @schedule.date.match(area)
  end

  def checked_t(area)
    @schedule.time.nil? ? false : @schedule.time.match(area)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_show.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="media">
  <% if @messages.present? %>
    <ul class="mail-list">
      <% @messages.each do |message| %>
            <li><%= message.body.html_safe %> <small class="pull-right time"><i class="fa fa-clock-o"></i> <%= message.created_at.strftime("%F %T") %></small></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="message-form">
  <%= form_for @message, :url => url_for(:controller => 'messages', :action => 'create'), :method => 'post', remote: true  do |f| %>

  <div class="field">
    <%= f.text_area :body, autofocus: true, placeholder: 'Message', id: "message_field", :cols => 40, :rows => 4  %>
  </div>

  <%= f.hidden_field :conversation_id, :value => @conversation.id %>
  <%= f.hidden_field :provider_id, :value => @conversation.provider_id %>
  <%= f.hidden_field :user_id, :value =>  @conversation.user_id %>
  <%= f.hidden_field :userticks, :value =>  'blue' %>
  <%= f.submit "New Message", id: 'submit' %>

  <% end %>
</div>

app/views/conversations/_showmessages.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="media">
  <% if @messages.present? %>
    <ul class="mail-list">
      <% @messages.each do |message| %>
            <li><%= message.body.html_safe %> <small class="pull-right time"><i class="fa fa-clock-o"></i> <%= message.created_at.strftime("%F %T") %></small></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="message-form">
  <%= form_for @message, :url => url_for(:controller => 'messages', :action => 'create'), :method => 'post', remote: true  do |f| %>

  <div class="field">
    <%= f.text_area :body, autofocus: true, placeholder: 'Message', id: "message_field", :cols => 40, :rows => 4  %>
  </div>

  <%= f.hidden_field :conversation_id, :value => @conversation.id %>
  <%= f.hidden_field :provider_id, :value => @conversation.provider_id %>
  <%= f.hidden_field :user_id, :value =>  @conversation.user_id %>
  <%= f.hidden_field :providerticks, :value =>  'blue' %>
  <%= f.submit "New Message", id: 'submit' %>

  <% end %>  
</div>

app/views/conversations/allmessages.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="chatperson">
        <% @conversations.each_with_index do |conversation, index| %>
            <div class="namechat">
              <%= link_to User.find(conversation.user_id).firstname, showmessages_provider_path(id: current_provider, conversation_id: conversation.id), class: "display-button", :remote => true %>
            <% if conversation.messages.where(providerticks: 'green').count > 0 %>
              <div class="notification-icon">
                <span class="glyphicon glyphicon-envelope"></span>
                <span class="badge"><%= conversation.messages.where(providerticks: 'green').count %></span>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
      <% if @conversations.present? %>
        <div class="col-xs-12 col-sm-8 show-message">
          <span><h5>Click on the customer's name to view your conversation.</h5></span>
        </div>
      <% else %>
      <div class="alert alert-danger alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <span><h4>You have no conversations</h4></span>
        </div>
      <% end %>
  </div>
</div>

app/views/conversations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="chatperson">
        <% @conversations.each_with_index do |conversation, index| %>
            <div class="namechat">
              <%= link_to Provider.find(conversation.provider_id).firstname, conversation_path(user_id: current_user, id: conversation.id), class: "display-button", :remote => true %>
            <% if conversation.messages.where(userticks: 'green').count > 0 %>
              <div class="notification-icon">
                <span class="glyphicon glyphicon-envelope"></span>
                <span class="badge"><%= conversation.messages.where(userticks: 'green').count %></span>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= form_for @conversation do |f| %>
      </br>
      <div class="field">
        <%= f.label :provider %>
        <%= f.select :provider_id, options_for_select(@providers.collect { |provider| [provider.firstname, provider.id] }), {}, {} %>
      </div>
      <%= f.submit id: 'submit' %>
      <% end %>
    </div>
      <% if @conversations.present? %>
        <div class="col-xs-12 col-sm-8 show-message">
          <span><h5>Click on the provider's name to view your conversation.</h5></span>
        </div>
      <% else %>
      <div class="alert alert-danger alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <span><h4>You have no conversations</h4></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/show.js.erb
$('.show-message').html('<%= j (render(partial: 'conversations/show')) %>')

app/views/conversations/showmessages.js.erb
$('.show-message').html('<%= j (render(partial: 'conversations/showmessages')) %>')