config/routes.rb
Rails.application.routes.draw do

  devise_for :providers, :controllers => { registrations: 'providers/registrations', sessions: 'providers/sessions', passwords: 'providers/passwords'}
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticated :user do
    root 'users#index'
  end

  authenticated :provider do
    root 'providers#index'
  end

  get '/', to: 'pages#homepage'
  get '/homepage', to: 'pages#homepage', as: 'homepage'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/about', to: 'pages#about', as: 'about'

  get '/urgent', to: 'users#urgent', as: 'urgent'
  get '/result', to: 'users#result', as: 'result'
  get '/electricians', to: 'users#electricians', as: 'electricians'

  resources :users, only: [:index, :show] do
    member do
      resources :conversations
    end
    member do
      resources :messages, only: [:new, :create, :destroy]
    end
  end

  resources :providers, only: [:index, :show] do
    member do
      resources :comments
    end
    member do
      get '/allmessages', to: 'conversations#allmessages', as: 'allmessages'
      get '/showmessages/:conversation_id', to: 'conversations#showmessages', as: 'showmessages'
    end
    member do
      resources :schedules, only: [:show, :new, :create, :update, :edit]
    end
    member do
      post 'like'
      delete 'unlike'
      put 'book'
    end
  end

  resources :joblistings do
    member do
      put 'accept'
      put 'decline'
    end
  end
  resources :invoices

  namespace 'admin' do
    resources :joblistings
    resources :invoices

    resources :providers, only: [:index]
    resources :users, only: [:index]
    get 'statistics'
  end

  resources :payments, only: [:new, :show, :create]

end

app/models/joblisting.rb
class Joblisting < ApplicationRecord

  belongs_to :user
  has_many :job_attaches, dependent: :destroy
  accepts_nested_attributes_for :job_attaches, reject_if: :all_blank, allow_destroy: true
  has_one :invoice

  before_save do
    issue.gsub!(/[\[\]\"]/, '') if attribute_present?('issue')
    fixture.gsub!(/[\[\]\"]/, '') if attribute_present?('fixture')
  end

  enum status: {
    'created':    1,
    'pending':    2,
    'booked':     3,
    'completed':  4,
    'cancel':     5
  }

end

app/controllers/admin/joblistings_controller.rb
class Admin::JoblistingsController < ApplicationController

  before_action :is_admin?

  def index
    @joblistings = Joblisting.all.page(params[:page]).per_page(10)
    @all_projects_total_cost = 0
    Invoice.all.map { |invoice| @all_projects_total_cost += invoice.price }
  end

  def edit; end

  def update; end

  def destroy; end

  private

  def is_admin?
    if current_user && current_user.is_admin == false
      redirect_to users_path
    elsif current_provider
      redirect_to providers_path
    elsif current_user.nil? && current_provider.nil?
      redirect_to homepage_path
    end
  end

end

app/controllers/joblistings_controller.rb
class JoblistingsController < ApplicationController

  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :authenticate_provider!, only: %i[accept decline]

  before_action :set_joblisting, except: %i[index new create]

  def index
    @joblistings = if current_provider
                     current_provider.joblistings.page(params[:page]).per_page(10)
                   else
                     Joblisting.all.page(params[:page]).per_page(10)
                   end
  end

  def show; end

  def new
    @joblisting = Joblisting.new
  end

  def create
    @joblisting = Joblisting.new(joblisting_params)
    @joblisting.user = current_user
    @joblisting.status = 'created'
    if @joblisting.save
      redirect_to result_path(job_date: @joblisting.date)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @joblisting.update(joblisting_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy; end

  def accept
    @joblisting.update(status: 'booked')
    @conversation = Conversation.where(provider_id: current_provider.id, user_id: @joblisting.user_id).first_or_create
    @message = Message.new(conversation_id: @conversation.id, provider_id: current_provider.id, user_id: @joblisting.user_id, body: 'I have accepted your request!')
    @message.body = current_provider.firstname + ' : ' + @message.body
    @message.save
    @message.update(providerticks: 'blue')
    redirect_to providers_path
  end

  def decline
    @joblisting.update(provider_id: nil, status: 'cancel')
    @conversation = Conversation.where(provider_id: current_provider.id, user_id: @joblisting.user_id).first_or_create
    @message = Message.new(conversation_id: @conversation.id, provider_id: current_provider.id, user_id: @joblisting.user_id, body: 'I have declined your request. Please find another provider. Thank you!')
    @message.body = current_provider.firstname + ' : ' + @message.body + " #{view_context.link_to('View your Joblsitings here!', users_path)} "
    @message.save
    @message.update(providerticks: 'blue')
    redirect_to providers_path
  end

  private

  def joblisting_params
    params.require(:joblisting).permit(:description, :num_fixture, :job_address, :time, :date, :housing, fixture: [], issue: [], job_attaches_attributes: %i[id title image joblisting_id _destroy])
  end

  private

  def set_joblisting
    @joblisting = Joblisting.find(params[:id])
  end

end

app/helpers/joblistings_helper.rb
module JoblistingsHelper

  def checked_i(area)
    @joblisting.issue.nil? ? false : @joblisting.issue.match(area)
  end

  def checked_f(area)
    @joblisting.fixture.nil? ? false : @joblisting.fixture.match(area)
  end

end

app/views/admin/joblistings/_main_thead.html.erb
<td>#</td>
<td>Date created</td>
<td>Customer name</td>              
<td>Customer email</td>
<td>Job status</td>
<td>Provider name</td>              
<td>Provider email</td>
<td>Invoice status</td>
<td>Project value S$ (<%= number_with_delimiter(@all_projects_total_cost) %>)</td>

app/views/admin/joblistings/_row_detail.html.erb
<tr>
  <td><%= index + 1 %></td>
  <td><%= joblisting.created_at.strftime("%F")%></td>
  <td><%= joblisting.user.firstname.capitalize %></td>                
  <td><%= link_to "#{joblisting.user.email}", user_path(joblisting.user) %></td>
  <td><%= link_to "#{joblisting.status.capitalize}", joblisting_path(joblisting) %></td>
  <% if joblisting.status == 'created' || joblisting.status == 'cancel' %>
    <td>No provider</td>
    <td>N.A.</td>
    <td>No invoice</td>
    <td>N.A.</td>
  <% else %>  
    <%provider = Provider.find(joblisting.provider_id)%>
    <td><%= provider.firstname.capitalize %></td>                  
    <td><%= link_to "#{provider.email}", provider_path(provider) %></td>
    <% if joblisting.invoice %>
      <td><%= joblisting.invoice.status.capitalize %></td>
      <td><%= number_with_delimiter(joblisting.invoice.price) %></td>
    <% else %>
      <td>No invoice</td>
      <td>N.A.</td>
    <% end %>
  <% end %>
</tr>

app/views/admin/joblistings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>List of all jobs (<%= Joblisting.count %>)</h1>
        <div class="panel panel-default">
          <table class="table">
            <tr>
              <%= render partial: 'main_thead' %>
            </tr>
            <% @joblistings.each_with_index do |joblisting, index| %>
              <%= render partial: 'row_detail', locals: { joblisting: joblisting, index: index } %>
            <% end %>
          </table>
        </div>
      <%= will_paginate @joblistings %>
    </div>
  </div>
</div>