config/routes.rb
Rails.application.routes.draw do

  devise_for :providers, :controllers => { registrations: 'providers/registrations', sessions: 'providers/sessions', passwords: 'providers/passwords'}
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticated :user do
    root 'users#index'
  end

  authenticated :provider do
    root 'providers#index'
  end

  get '/', to: 'pages#homepage'
  get '/homepage', to: 'pages#homepage', as: 'homepage'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/about', to: 'pages#about', as: 'about'

  get '/urgent', to: 'users#urgent', as: 'urgent'
  get '/result', to: 'users#result', as: 'result'
  get '/electricians', to: 'users#electricians', as: 'electricians'

  resources :users, only: [:index, :show] do
    member do
      resources :conversations
    end
    member do
      resources :messages, only: [:new, :create, :destroy]
    end
  end

  resources :providers, only: [:index, :show] do
    member do
      resources :comments
    end
    member do
      get '/allmessages', to: 'conversations#allmessages', as: 'allmessages'
      get '/showmessages/:conversation_id', to: 'conversations#showmessages', as: 'showmessages'
    end
    member do
      resources :schedules, only: [:show, :new, :create, :update, :edit]
    end
    member do
      post 'like'
      delete 'unlike'
      put 'book'
    end
  end

  resources :joblistings do
    member do
      put 'accept'
      put 'decline'
    end
  end
  resources :invoices

  namespace 'admin' do
    resources :joblistings
    resources :invoices

    resources :providers, only: [:index]
    resources :users, only: [:index]
    get 'statistics'
  end

  resources :payments, only: [:new, :show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :provider

end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user
  belongs_to :provider

  validates :user_id, uniqueness: { scope: :provider_id }

  has_many :messages, dependent: :destroy

end

app/models/invoice.rb
class Invoice < ApplicationRecord

  belongs_to :provider
  belongs_to :joblisting

  enum status: {
    'Awaiting Payment': 1,
    'Payment Received': 2,
    'Payment Released': 3
  }

end

app/models/job_attach.rb
class JobAttach < ApplicationRecord

  mount_uploader :image, JobImageUploader
  belongs_to :joblisting

end

app/models/joblisting.rb
class Joblisting < ApplicationRecord

  belongs_to :user
  has_many :job_attaches, dependent: :destroy
  accepts_nested_attributes_for :job_attaches, reject_if: :all_blank, allow_destroy: true
  has_one :invoice

  before_save do
    issue.gsub!(/[\[\]\"]/, '') if attribute_present?('issue')
    fixture.gsub!(/[\[\]\"]/, '') if attribute_present?('fixture')
  end

  enum status: {
    'created':    1,
    'pending':    2,
    'booked':     3,
    'completed':  4,
    'cancel':     5
  }

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :provider

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation
  belongs_to :user
  belongs_to :provider

end

app/models/provider.rb
class Provider < ApplicationRecord

  mount_uploader :avatar, ProviderAvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes
  has_many :invoices
  has_many :provider_attaches
  has_many :joblistings
  has_one :schedule
  has_many :conversations
  has_many :messages
  has_many :comments

  accepts_nested_attributes_for :provider_attaches, reject_if: :all_blank, allow_destroy: true

  scope :sort_exp, -> { order('experience DESC') }

  enum experience: {
    "< 1 year":       1,
    "1 to 3 years":   2,
    "3 to 5 years":   3,
    "> 5 years":      4
  }

end

app/models/provider_attach.rb
class ProviderAttach < ApplicationRecord

  mount_uploader :image, ProviderAttachUploader
  belongs_to :provider

end

app/models/schedule.rb
class Schedule < ApplicationRecord

  belongs_to :provider

  validates :date, :time, presence: true

  scope :weekends, -> { where(date: 'weekends') }
  scope :weekdays, -> { where(date: 'weekdays') }
  scope :alldays, -> { where(date: 'all') }

  before_save do
    date.gsub!(/[\[\]\"]/, '') if attribute_present?('date')
    time.gsub!(/[\[\]\"]/, '') if attribute_present?('time')
  end

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :joblistings
  has_many :likes
  has_many :conversations
  has_many :messages
  has_many :comments
  has_many :providers, through: :likes
  has_many :invoices, through: :joblistings

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  TRANSACTION_SUCCESS_STATUSES = [
    Braintree::Transaction::Status::Authorizing,
    Braintree::Transaction::Status::Authorized,
    Braintree::Transaction::Status::Settled,
    Braintree::Transaction::Status::SettlementConfirmed,
    Braintree::Transaction::Status::SettlementPending,
    Braintree::Transaction::Status::Settling,
    Braintree::Transaction::Status::SubmittedForSettlement
  ].freeze

  def new
    @client_token = Braintree::ClientToken.generate
    @@user_invoice = Invoice.find(params[:id])
    @invoice = @@user_invoice
  end

  def show
    @transaction = Braintree::Transaction.find(params[:id])
    @invoice = Invoice.find(params[:invoice_id])
    @result = _create_result_hash(@transaction)
  end

  def create
    @invoice = @@user_invoice
    amount = params['amount'] # In production you should not take amounts directly from clients
    nonce = params['payment_method_nonce']

    result = Braintree::Transaction.sale(
      amount: amount,
      payment_method_nonce: nonce,
      options: {
        submit_for_settlement: true
      }

    )

    if result.success? || result.transaction
      @invoice.update(status: 2)
      redirect_to payment_path(result.transaction.id, invoice_id: @invoice.id)
    else
      error_messages = result.errors.map { |error| "Error: #{error.code}: #{error.message}" }
      flash[:error] = error_messages
      redirect_to new_payment_path
    end
  end

  def _create_result_hash(transaction)
    status = transaction.status

    result_hash = if TRANSACTION_SUCCESS_STATUSES.include? status
                    {
                      header: 'Sweet Success!',
                      icon: 'success',
                      message: "Thank you, your payment for Invoice ref: #{@invoice.invoice_ref} has been successfully processed."
                    }
                  else
                    {
                      header: 'Transaction Failed',
                      icon: 'fail',
                      message: "Your transaction has a status of #{status}.Please try again."
                    }
                  end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def checked_d(area)
    @schedule.date.nil? ? false : @schedule.date.match(area)
  end

  def checked_t(area)
    @schedule.time.nil? ? false : @schedule.time.match(area)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/payments/new.html.erb
<div class="wrapper">
  <div class="checkout container">
    <div class="content">

      <header>

      </header>

      <%= form_tag(payments_path, method: "post", id: "payment-form") do %>
        <section>
          <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
              <div class="panel panel-default">
                <div class="panel-heading"><h3>Payment Information<h3></div>
                <table class="table">
                  <tr>
                  </tr>
                  <tr>
                    <td>Project Description:</td>
                    <td><%= link_to "#{@invoice.joblisting.description}", joblisting_path(@invoice.joblisting), target: :_blank %></td>
                  </tr>
                  <tr>
                    <td>Electrician name:</td>
                    <td><%= link_to "#{@invoice.provider.firstname}", provider_path(@invoice.provider), target: :_blank %></td>
                  </tr>
                  <tr>
                    <td>Invoice number:</td>
                    <td><%= link_to "#{@invoice.invoice_ref}", invoice_path(@invoice), target: :blank %></td>
                  </tr>
                  <tr>
                    <td>Total Amount (in SGD):</td>
                    <td>
                      <label for="amount">
                        <div class="input-wrapper amount-wrapper">
                          <input id="amount" name="amount" type="tel" min="1" placeholder="Amount" readonly="true" value= "<%= @invoice.price %>" size= <%= "#{@invoice.price.to_s.length - 2}" %>>
                        </div>
                      </label>
                    </td>
                  <tr>
                </table>
              </div>
            </div>
          </div>
          <h3 style="text-align:center;">Pls Proceed with the Payment Below:</h3>
          <div class="bt-drop-in-wrapper well">
            <div id="bt-dropin"></div>
            <input type="hidden" id="nonce" name="payment_method_nonce" />
            <button class="btn btn-success btn-block" type="submit"><span>Pay now</span></button>
            <% end %>
          </div>
        </section>
    <br><br>
    </div>
  </div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.2.0/js/dropin.min.js"></script>
<script>
  var form = document.querySelector('#payment-form');
  var client_token = "<%= @client_token %>";
  braintree.dropin.create({
    authorization: client_token,
    container: '#bt-dropin',
    paypal: {
      flow: 'vault'
    }
  }, function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }
        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
  var checkout = new Demo({
    formID: 'payment-form'
  });
</script>

app/views/payments/show.html.erb
<div class='container'>
  <div class="row">
    <div class="col-xs-4 payment-show">
      <div class="panel panel-success">
        <div class="panel-heading"><h3>Transaction Details</h3></div>
        <table class='payment-show-table'>
          <tbody>
            <tr>
              <th>Transaction ID:</th>
              <td><%= @transaction.id %></td>
            </tr>
            <tr>
              <th>Amount:</th>
              <td><%= @transaction.amount %></td>
            </tr>
            <tr>
              <th>Status:</th>
              <td><%= @transaction.status %></td>
            </tr>
            <tr>
              <th>Created at:</th>
              <td><%= @transaction.created_at %></td>
            </tr>
            <tr>
              <th>Updated at:</th>
              <td><%= @transaction.updated_at %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-xs-7">

      <% if @result %>
      <h1><%= @result[:header] %></h1>
      <%= image_tag "success-icon-mobile-2x.png" %>
      <section>
        <p><%= @result[:message] %></p>
        <% else %>
        <section>
          <p>Your transaction has failed.Please try again.</p>
        </section>
        <% end %>
        <div>
          <a class="button primary back" href="/users/">
            <span>Return to Dashboard</span>
          </a>
        </div>
    </div>
  </div>
</div>